src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Serializer\SerializerInterface;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[Uploadable]
class Produit implements SerializerInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: 'text')]
    private ?string $description = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $couleur = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $taille = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $collection = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $photo = null;

    #[UploadableField(mapping: 'produits', fileNameProperty: 'photo')]
    #[Ignore]
    private ?File $fichier = null;

    #[ORM\Column(type: 'float')]
    private float $prix = 0.0;

    #[ORM\Column(type: 'integer')]
    private int $stock = 0;

    #[ORM\Column(type: 'datetime_immutable', length: 255)]
    private \DateTimeImmutable $date_enregistrement;

    public function __construct()
    {
        $this->date_enregistrement = new \DateTimeImmutable();
    }

    public function __toString()
    {
        return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setFichier(?File $fichier = null): self
    {
        $this->fichier = $fichier;
        if ($this->fichier instanceof UploadedFile) {
            $this->date_enregistrement = new \DateTimeImmutable();
        }
        return $this;
    }

    public function getFichier(): ?File
    {
        return $this->fichier;
    }


    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getTaille(): ?string
    {
        return $this->taille;
    }

    public function setTaille(string $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getCollection(): ?string
    {
        return $this->collection;
    }

    public function setCollection(string $collection): self
    {
        $this->collection = $collection;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeImmutable
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeImmutable $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function serialize(mixed $data, string $format, array $context = []): string
    {
        // TODO: Implement serialize() method.
    }

    public function deserialize(mixed $data, string $type, string $format, array $context = []): mixed
    {
        // TODO: Implement deserialize() method.
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('couleur', ColorType::class)
            ->add('taille', ChoiceType::class, [
                'choices' => [
                    'XS' => 'XS',
                    'S' => 'S',
                    'M' => 'M',
                    'L' => 'L',
                    'XL' => 'XL',
                    'XXL' => 'XXL',
                    'XXXL' => 'XXXL'
                ]
            ])
            ->add('collection', ChoiceType::class, [
                'choices' => [
                    'F' => 'F',
                    'M' => 'M'
                ]
            ])
            ->add('fichier', FileType::class)
            ->add('prix')
            ->add('stock')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProduitRepository $produitRepository): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $produitRepository->add($produit, true);

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, ProduitRepository $produitRepository): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $produitRepository->add($produit, true);

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, ProduitRepository $produitRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $produitRepository->remove($produit, true);
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    <div class="card">
        <div class="card-body">
            {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}
        </div>
    </div>

    <a class="btn btn-primary" href="{{ path('app_produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <a class="btn btn-primary" href="{{ path('app_produit_new') }}">Create new</a>
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Couleur</th>
                    <th>Taille</th>
                    <th>Collection</th>
                    <th>Photo</th>
                    <th>Prix</th>
                    <th>Stock</th>
                    <th>Date_enregistrement</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for produit in produits %}
                    <tr>
                        <td>{{ produit.id }}</td>
                        <td>{{ produit.titre }}</td>
                        <td>{{ produit.description }}</td>
                        <td style="background: {{ produit.couleur }}">&nbsp;</td>
                        <td>{{ produit.taille }}</td>
                        <td>{{ produit.collection }}</td>
                        <td>
                            <img height="auto" src="{{ produit.photo }}" alt="">
                        </td>
                        <td>{{ produit.prix }}</td>
                        <td>{{ produit.stock }}</td>
                        <td>{{ produit.dateEnregistrement ? produit.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <a href="{{ path('app_produit_show', {'id': produit.id}) }}">show</a>
                            <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    <div class="card">
        <div class="card-body">
            {{ include('produit/_form.html.twig') }}
        </div>
    </div>

    <a class="btn btn-primary" href="{{ path('app_produit_index') }}">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <div class="card">
        <div class="card-body">
            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ produit.id }}</td>
                </tr>
                <tr>
                    <th>Titre</th>
                    <td>{{ produit.titre }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ produit.description }}</td>
                </tr>
                <tr>
                    <th>Couleur</th>
                    <td>{{ produit.couleur }}</td>
                </tr>
                <tr>
                    <th>Taille</th>
                    <td>{{ produit.taille }}</td>
                </tr>
                <tr>
                    <th>Collection</th>
                    <td>{{ produit.collection }}</td>
                </tr>
                <tr>
                    <th>Photo</th>
                    <td>{{ produit.photo }}</td>
                </tr>
                <tr>
                    <th>Prix</th>
                    <td>{{ produit.prix }}</td>
                </tr>
                <tr>
                    <th>Stock</th>
                    <td>{{ produit.stock }}</td>
                </tr>
                <tr>
                    <th>Date_enregistrement</th>
                    <td>{{ produit.dateEnregistrement }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <a class="btn btn-primary" href="{{ path('app_produit_index') }}">back to list</a>
    <a class="btn btn-primary" href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>
    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}